version: '3'
services:
  selenium-hub:
    image: selenium/hub:4.34.0
    container_name: selenium-hub
    ports:
      - '4442:4442'
      - '4443:4443'
      - '4444:4444'
      - '5900:5900'
    networks:
      - selenium-network

  chrome:
    image: selenium/node-chrome:4.34.0-20250717
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=1
    networks:
      - selenium-network

  firefox:
    image: selenium/node-firefox:4.34.0-20250717
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_MAX_INSTANCES=1
    networks:
      - selenium-network

  wdio-tests:
    build:
      context: .
    depends_on:
      - selenium-hub
      - firefox
      - chrome
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh -c "rm -rf /app/allure-results && mkdir -p /app/allure-results && npx wdio run ./config/wdio.docker.conf.js"
    networks:
      - selenium-network

  allure:
    image: frankescobar/allure-docker-service
    ports:
      - '5050:5050'
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
    networks:
      - selenium-network

networks:
  selenium-network:
    driver: bridge
